server:
  port: 8090

spring:
  application:
    name: "loans"
  profiles:
    active: "qa"
  jpa:
    show-sql: true
    open-in-view: false
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:mysql://localhost:3307/loansdb
    username: root
    password: root
  config:
    import: "optional:configserver:http://localhost:8071/"  #if your application properties are really important you can remove optional prefix


management:
  endpoint:
    web:
      exposure:
        include: "*"