spring:
  application:
    name: "configserver"
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/emirhanbaran0/eazybank-config"
          default-label: main # default branch
          timeout: 5 # should wait until 5 seconds if it's not successful to connect config server should throw an exception
          clone-on-start: true
          force-pull: true # reading always the latest config from the main branch


  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true  # "/actuator/health/readiness"
    liveness-state:
      enabled: true  # "/actuator/health/readiness"
  endpoint:
    health:
      probes:
        enabled: true

encrypt:
  key:  "C1HANG1R-K3N3DY"  #For encrypting our application properties.

server:
  port: 8071